// Export via CodePen's "prefill" form POST: no GitHub token, no backend - just a
// hidden form submitted to codepen.io, which opens a new pen with the data baked
// in. Saving that pen (optional) happens in the visitor's own CodePen account,
// same idea as https://blog.codepen.io/documentation/prefill/.

const POSITION = [-1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1, -1];
const UV = [0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1];

const HTML = `<canvas id="canvas"></canvas>`;

const CSS = `html, body {
  margin: 0;
  height: 100%;
}

#canvas {
  display: block;
  width: 100%;
  height: 100%;
}`;

// Only the raymarch-sphere preset declares this uniform, but without it a shader
// that does would just get cameraPos stuck at (0,0,0) - inside the scene it's meant
// to be looking at from a distance - so the export needs the same orbit math as
// orbit-controls-plugin.js whenever a shader asks for it.
const CAMERA_UNIFORM = /\bcameraPos\b/;

// Mirrors OrbitControlsPlugin's defaults and trackball math (drag to orbit, wheel
// to zoom) since that plugin isn't available outside the lab.
const CAMERA_JS = `
let azimuth = 0.6;
let elevation = 0.4;
let distance = 4;
const MAX_ELEVATION = 1.5;
const SENSITIVITY = Math.PI * 2;
const ZOOM_SENSITIVITY = 0.001;

function clamp(x, min, max) {
  return Math.min(Math.max(x, min), max);
}

let lastX = null;
let lastY = null;

canvas.addEventListener('pointerdown', (e) => {
  lastX = e.clientX / canvas.clientWidth;
  lastY = e.clientY / canvas.clientHeight;
});
window.addEventListener('pointermove', (e) => {
  if (lastX === null) return;
  const x = e.clientX / canvas.clientWidth;
  const y = e.clientY / canvas.clientHeight;
  azimuth += (x - lastX) * SENSITIVITY;
  elevation = clamp(elevation + (y - lastY) * SENSITIVITY, -MAX_ELEVATION, MAX_ELEVATION);
  lastX = x;
  lastY = y;
});
window.addEventListener('pointerup', () => {
  lastX = null;
  lastY = null;
});
canvas.addEventListener('wheel', (e) => {
  e.preventDefault();
  distance = clamp(distance * Math.exp(e.deltaY * ZOOM_SENSITIVITY), 1, 20);
}, { passive: false });

const cameraPosLoc = gl.getUniformLocation(program, 'cameraPos');
function updateCameraPos() {
  const cosElevation = Math.cos(elevation);
  gl.uniform3f(
    cameraPosLoc,
    distance * cosElevation * Math.sin(azimuth),
    distance * Math.sin(elevation),
    distance * cosElevation * Math.cos(azimuth),
  );
}
`;

// A small dependency-free WebGL2 setup that plays the same role as the shader-art
// element in the lab itself: same uniform names (resolution/time), same attributes
// (position/uv) and buffers, so a shader written in the lab keeps working unchanged.
function buildJs(fragCode, vertCode) {
  const needsCamera = CAMERA_UNIFORM.test(fragCode) || CAMERA_UNIFORM.test(vertCode);
  return `// Generated by Shader Lab: a minimal WebGL2 setup, no dependencies.
const canvas = document.getElementById('canvas');
const gl = canvas.getContext('webgl2');

const vertSource = ${JSON.stringify(vertCode)};
const fragSource = ${JSON.stringify(fragCode)};

function compileShader(type, source) {
  const shader = gl.createShader(type);
  gl.shaderSource(shader, source);
  gl.compileShader(shader);
  if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
    throw new Error(gl.getShaderInfoLog(shader));
  }
  return shader;
}

const program = gl.createProgram();
gl.attachShader(program, compileShader(gl.VERTEX_SHADER, vertSource));
gl.attachShader(program, compileShader(gl.FRAGMENT_SHADER, fragSource));
gl.linkProgram(program);
if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
  throw new Error(gl.getProgramInfoLog(program));
}
gl.useProgram(program);

function addBuffer(name, size, data) {
  const buffer = gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(data), gl.STATIC_DRAW);
  const loc = gl.getAttribLocation(program, name);
  if (loc !== -1) {
    gl.enableVertexAttribArray(loc);
    gl.vertexAttribPointer(loc, size, gl.FLOAT, false, 0, 0);
  }
  return data.length / size;
}

const vertexCount = addBuffer('position', 2, ${JSON.stringify(POSITION)});
addBuffer('uv', 2, ${JSON.stringify(UV)});

const resolutionLoc = gl.getUniformLocation(program, 'resolution');
const timeLoc = gl.getUniformLocation(program, 'time');
${needsCamera ? CAMERA_JS : ''}
function resize() {
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  canvas.width = canvas.clientWidth * dpr;
  canvas.height = canvas.clientHeight * dpr;
  gl.viewport(0, 0, canvas.width, canvas.height);
}
new ResizeObserver(resize).observe(canvas);

const start = performance.now();
function frame(now) {
  gl.uniform2f(resolutionLoc, canvas.width, canvas.height);
  gl.uniform1f(timeLoc, (now - start) * 0.001);
  ${needsCamera ? 'updateCameraPos();' : ''}
  gl.drawArrays(gl.TRIANGLES, 0, vertexCount);
  requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
`;
}

// Confirmed by testing: target="_blank" makes CodePen's backend respond with a 500
// (likely their bot/CSRF protection distrusting a POST into a fresh, opener-less
// browsing context) - same-tab navigation works fine.
/** Navigates to a CodePen prefilled with the current frag/vert shaders. */
export function openInCodePen({ frag, vert, title = 'Shader Lab' }) {
  const data = {
    title,
    description: 'Exported from Shader Lab (https://github.com/learosema/talk-shader-programmierung).',
    html: HTML,
    css: CSS,
    js: buildJs(frag, vert),
    editors: '111', // HTML, CSS and JS all open
  };

  const form = document.createElement('form');
  form.action = 'https://codepen.io/pen/define';
  form.method = 'POST';
  form.style.display = 'none';

  const input = document.createElement('input');
  input.type = 'hidden';
  input.name = 'data';
  input.value = JSON.stringify(data);
  form.appendChild(input);

  document.body.appendChild(form);
  form.submit();
  form.remove();
}
